### PR TITLE
Changes to match other bls12_381 libraries

### PR DESCRIPTION
**Pull request by mikelodder7**
Added methods to match other bls12-381 libraries (like bls12_381_plus) such as consistent serialization, convenience methods for hex and byte ordering and use const values which is more consistent with Rust-crypto.

### CODE REVIEW

**Comment by vmx** [comment]
Thanks for the PR, it contains a lot of good changes.

Currently `blstrs` tries to be a drop-in replacement for the [`bls12_381` crate](https://crates.io/crates/bls12_381). Some of your changes are currently incompatible with that.

You maintain the [`blst12_381_plus` fork](https://crates.io/crates/bls12_381_plus). For me, one of the key things about open source is collaboration and trying to do what's best for the community/ecosystem. While sometimes forks are needed, I really try to keep them to a minimum. Have you tried to upstream your changes to `bls12_381`? I think it would be great if we could get those forks together and then making `blstrs` compatible to that.

**Comment by mikelodder7** [comment]
> Thanks for the PR, it contains a lot of good changes.
> 
> Currently `blstrs` tries to be a drop-in replacement for the [`bls12_381` crate](https://crates.io/crates/bls12_381). Some of your changes are currently incompatible with that.
> 
> You maintain the [`blst12_381_plus` fork](https://crates.io/crates/bls12_381_plus). For me, one of the key things about open source is collaboration and trying to do what's best for the community/ecosystem. While sometimes forks are needed, I really try to keep them to a minimum. Have you tried to upstream your changes to `bls12_381`? I think it would be great if we could get those forks together and then making `blstrs` compatible to that.

Yes I have in the past but they are locked on version 1.56 and in order to incorporate the new hash_to_curve interfaces in elliptic-curve 0.13, this restriction has to be lifted. Until they do, I can't raise a PR to them. Happy to keep a fork of this repo until then.

**Comment by mikelodder7** [comment]
That being said, `bls12_381_plus` is 98% compatible with `bls12_381`.

**Comment by mikelodder7** [comment]
Going to close for now. Perhaps once `bls12_381_plus` is merged then I can raise a PR again.

**Comment by mikelodder7** [comment]
@daira Done https://github.com/zkcrypto/bls12_381/pull/107/files

**Pull request closed without merging**
