### PR TITLE
Merge 0-1 branch into master

### LINKED ISSUE #18: Merge 0-1 branch into master

### PR DESCRIPTION
**Pull request by dignifiedquire**
Closes #18

### CODE REVIEW

**Comment by cryptonemo** [comment]
Clippy!

**Comment by dignifiedquire** [comment]
> Clippy!

😱

**Review by cryptonemo — APPROVED** [review]
Looks good, but let's wait until the upgrade is complete?  Call it superstition of sorts.

**Comment by dignifiedquire** [comment]
`master` is already on the `blst` with breaking changes, which is why the `0-1` branch exists, so I think we can merge this happily, just not gonna cut a release yet, as there are some additional things from the new blst I might want to pull in. Or was there another concern you had?

**Pull request merged**
